baseurl = "https://legionviking.se/"
title = "Legion Viking"
theme = "legv"
languageCode = "sv"
enableRobotsTXT = true
diary = "Dagbok"
paginate = 25

[menu]
  [[menu.header]]
    name = "dokument"
    weight = 4
    url = "/docs"
  [[menu.header]]
    name = "historia"
    weight = 3
    url = "/timeline"
  [[menu.header]]
    name = "vietnam"
    parent = "dagbok"
    weight = 1
    url = "/vietnam"
  [[menu.header]]
    name = "ww2"
    parent =  "dagbok"
    weight = 2
    url = "/ww2"
  [[menu.header]]
    name = "dagbok"
    weight = 2
    url = "/diary"
  [[menu.header]]
    name = "moddar"
    weight = 1
    url = "/mods"

[params]
  Name = "Legion Viking"
  HeaderUsername = "legionär"
  HeaderHostname = "legionviking"
  About = "Ännu en arma community från Sverige."
  ProfilePicture = "/logo.png"
